#!/bin/bash

echo "Cloning Vundle into profile "

git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim

echo "Removing not necessary files i.e. README, .git"

rm README && \
rm -rf .git 

echo "Copying profile files into \$HOME"
cp .* $HOME/
