#!/bin/bash

echo "Cloning Vundle into profile "
mkdir -p $HOME/.vim/

git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim

mkdir -p bundle && cd bundle

./install_pythonmode

echo "Removing not necessary files i.e. README, .git"

rm README && \
rm -rf .git 

echo "Copying profile files into \$HOME"
cp .* $HOME/
