#!/bin/bash

echo "Cloning Vundle into profile "
mkdir -p $HOME/.vim/
git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim

ln -s $(pwd)/.vimrc ~/.vimrc
ln -s $(pwd)/.vimrc.simplenote ~/.vimrc.simplenote
ln -s $(pwd)/.profile ~/.profile
ln -s $(pwd)/.profile.prompt ~/.profile.prompt
ln -s $(pwd)/.profile.aliases ~/.profile.aliases
ln -s $(pwd)/.profile.scripts ~/.profile.scripts
ln -s $(pwd)/.profile.setvi ~/.profile.setvi
ln -s $(pwd)/.profile.pyenv ~/.profile.pyenv
ln -s $(pwd)/.profile.tmuxp ~/.profile.tmuxp
ln -s $(pwd)/.profile.i3 ~/.profile.i3
ln -s $(pwd)/.profile.sdkman ~/.profile.sdkman
ln -s $(pwd)/.tmux.conf ~/.tmux.conf
ln -s $(pwd)/.bashrc ~/.bashrc
